dist: bionic
language:
  - cpp
branches:
  only:
  - master
compiler:
  - gcc
before_install:
  - sudo apt-get update
  - sudo apt-get install -y --fix-missing build-essential
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
before_script:
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - gcc -v && g++ -v && cmake --version
  - cd ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/google/googletest.git googletest
  - cd googletest && mkdir build 
  - cd build && cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/local .. && make && make install && cp ../googletest/src/* /tmp/local/src
script:
  - cd ${TRAVIS_BUILD_DIR} && mkdir build
  - cd build && cmake .. && make
  - make test
